spring.application.name=conversation-practice-village-back

# Hibernate configuration
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Google Gemini API Settings
google.gemini.api-key=${GEMINI_API_KEY}
google.gemini.base-url=https://generativelanguage.googleapis.com
google.gemini.api-version=v1
google.gemini.models=gemini-2.5-flash-lite

# ?? ?? - AiService ??? ?? ???
logging.level.com.example.conversationpracticevillageback.domain.AI.AiService=DEBUG

